<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class RutasSeeder extends Seeder
{
    public function run()
    {
        $generalRoutes = [
            'JUAREZ|CHIHUAHUA' => 375,
            'CHIHUAHUA|JUAREZ' => 375,
            'EL PASO|CHIHUAHUA' => 415,
            'CHIHUAHUA|EL PASO' => 415,
            'PRECOS|CHIHUAHUA' => 360,
            'CHIHUAHUA|PRECOS' => 360,
        ];

        $pacificoRoutes = [
            'JUAREZ|OBREGON' => 1021,
            'OBREGON|JUAREZ' => 1021,
            'JUAREZ|GUAMUCHIL' => 1330,
            'GUAMUCHIL|JUAREZ' => 1330,
            'OBREGON|GUAMUCHIL' => 328,
            'GUAMUCHIL|OBREGON' => 328,
            'CHIHUAHUA|OBREGON' => 1131,
            'OBREGON|CHIHUAHUA' => 1131,
            'MOCHIS|GUAMUCHIL' => 106,
            'GUAMUCHIL|MOCHIS' => 106,
            'JUAREZ|BACUM' => 1004,
            'BACUM|JUAREZ' => 1004,
            'MOCHIS|OBREGON' => 232,
            'OBREGON|MOCHIS' => 232,
            'BACUM|OBREGON' => 45,
            'OBREGON|BACUM' => 45,
            'CHIHUAHUA|MOCHIS' => 1363,
            'MOCHIS|CHIHUAHUA' => 1363,
            'JUAREZ|NAVOJOA' => 1081,
            'NAVOJOA|JUAREZ' => 1081,
            'CANANEA|OBREGON' => 551,
            'OBREGON|CANANEA' => 551,
            'JUAREZ|CANANEA' => 457,
            'CANANEA|JUAREZ' => 457,
            'JUAREZ|ETCHO' => 1118,
            'ETCHO|JUAREZ' => 1118,
            'ETCHO|OBREGON' => 97,
            'OBREGON|ETCHO' => 97,
            'OBREGON|NAVOJOA' => 67,
            'NAVOJOA|OBREGON' => 67,
            'ETCHO|NAVOJOA' => 30,
            'NAVOJOA|ETCHO' => 30,
            'OBREGON|CUAHU' => 1236,
            'CUAHU|OBREGON' => 1236,
            'ETCHO|JANOS' => 888,
            'JANOS|ETCHO' => 888,
            'JANOS|OBREGON' => 795,
            'OBREGON|JANOS' => 795,
            'NOGALES|JUAREZ' => 603,
            'JUAREZ|NOGALES' => 603,
            'S. RIO COL.|HERMOSILLO' => 630,
            'HERMOSILLO|OBREGON' => 255,
            'CHIHUAHUA|CUAHU' => 145,
            'CUAHU|CHIHUAHUA' => 145,
            'S. RIO COL.|EMPALME' => 772,
            'EMPALME|OBREGON' => 120,
            'JANOS|GUAMUCHIL' => 1120,
            'GUAMUCHIL|JANOS' => 1120,
            'JUAREZ|JANOS' => 219,
            'JANOS|JUAREZ' => 219,
            'JANOS|MOCHIS' => 1027,
            'JUAREZ|CUAHU' => 480,
            'CUAHU|JUAREZ' => 480,
            'S. RIO COL.|JUAREZ' => 1037,
            'JUAREZ|S. RIO COL.' => 1037,
            'CHIHUAHUA|JANOS' => 348,
            'JANOS|CHIHUAHUA' => 348,
            'S. RIO COL.|OBREGON' => 885,
            'JUAREZ|MOCHIS' => 1254,
            'MOCHIS|JUAREZ' => 1224,
            'JUAREZ|HERMOSILLO' => 800,
        ];

        $clientRoutes = [
            'GYSA ASCENCION|FLETES SOTELO' => 200,
            'APTIV GUAMUCHIL FV52|APTIV / RIO BRAVO 7 FV32' => 1330,
            'APTIV GUAMUCHIL FV52|FLETES SOTELO' => 1330,
            'ATLAS AEROSPACE|FLETES SOTELO' => 375,
            'ATLAS AEROSPACE|PRECOS ZARAGOZA' => 375,
            'BASE SOTELO CHIHUAHUA|CASETA DE VILLA AHUMADA' => 130,
            'BASE SOTELO CHIHUAHUA|FLETES SOTELO' => 375,
            'BASE SOTELO CHIHUAHUA|PRECOS ZARAGOZA' => 375,
            'BASE SOTELO CHIHUAHUA|YARDA DEL SIETE' => 375,
            'DTR|PRECOS ZARAGOZA' => 375,
            'DTR|FLETES SOTELO' => 375,
            'GYSA OBREGON 2|FLETES SOTELO' => 1021,
            'IMPULSORA GANE|FLETES SOTELO' => 375,
            'NORDAM|FLETES SOTELO' => 375,
            'NORDAM|PRECOS ZARAGOZA' => 375,
            'PACTIV DE MEXICO S. DE R.L DE C.V.|FLETES SOTELO' => 375,
            'SAFRAN PLANTA 3/OSM/OXYGEN SYSTEMS|FLETES SOTELO' => 375,
            'SAFRAN PLANTA 3 /WWM/ WATER & WASTE MEX (MONOGRAM)|FLETES SOTELO' => 375,
            'SMTC PLANTA 1|FLETES SOTELO' => 375,
            'THUASNE MX|FLETES SOTELO' => 375,
            'XOMOX CHIHUAHUA S.A DE C.V.|FLETES SOTELO' => 375,
            'YARDA SOTELO OBREGON|FLETES SOTELO' => 1021,
            'YARDA SOTELO OBREGON|PRECOS ZARAGOZA' => 1021,
            'YAZAKI COMPONENTES PLANTA 3|FLETES SOTELO' => 375,
            'APTIV MOCHIS FV59|YARDA SOTELO OBREGON' => 232,
            'DEMINSA SA DE CV|YARDA SOTELO OBREGON' => 255,
            'FLETES SOTELO|APTIV GUAMUCHIL FV52' => 1330,
            'FLETES SOTELO|BASE SOTELO CHIHUAHUA' => 375,
            'FLETES SOTELO|IMPULSORA GANE' => 375,
            'FLETES SOTELO|YARDA SOTELO OBREGON' => 1021,
            'FLETES SOTELO|YAZAKI COMPONENTES PLANTA 3' => 375,
            'GYSA  CDJ|FLETES SOTELO' => 375,
            'GYSA BACUM|GYSA OBREGON PDC' => 45,
            'GYSA BACUM|YARDA SOTELO OBREGON' => 45,
            'GYSA ETCHOJOA|GYSA OBREGON PDC' => 97,
            'GYSA NAVOJOA|GYSA OBREGON ODC' => 67,
            'GYSA NAVOJOA|GYSA OBREGON PDC' => 67,
            'GYSA NAVOJOA|YARDA SOTELO OBREGON' => 67,
            'GYSA OBREGON ODC|GYSA BACUM' => 45,
            'YARDA SOTELO OBREGON|GYSA BACUM' => 45,
            'GYSA OBREGON ODC|GYSA ETCHOJOA' => 97,
            'GYSA OBREGON ODC|GYSA NAVOJOA' => 67,
            'SAFRAN PLANTA 1 /EMX/ EVACUATION SY (AIR CRUSIERS)|FLETES SOTELO' => 375,
            'YARDA SOTELO OBREGON|GYSA ETCHOJOA' => 97,
            'APTIV / RIO BRAVO 7 FV32|APTIV GUAMUCHIL FV52' => 1330,
            'APTIV MOCHIS FV59|APTIV GUAMUCHIL FV52' => 106,
            'BASE SOTELO CHIHUAHUA|APTIV MOCHIS FV59' => 1363,
            'BASE SOTELO CHIHUAHUA|APTIV RIO BRAVO 4 FV33' => 375,
            'BASE SOTELO CHIHUAHUA|GYSA JUAREZ JDC' => 375,
            'BASE SOTELO CHIHUAHUA|GYSA OBREGON PDC' => 1131,
            'COFICAB LEON, S. DE R.L. DE C.V. / PLANTA JUAREZ|TE CONNECTIVITY HERMOSILLO' => 800,
            'COFICAB LEON, S. DE R.L. DE C.V. / PLANTA JUAREZ|GYSA OBREGON PDC' => 1021,
            'FLETES SOTELO|APTIV MOCHIS FV59' => 1224,
            'FLETES SOTELO|GYSA ASCENCION' => 200,
            'FLETES SOTELO|GYSA BACUM' => 1004,
            'FLETES SOTELO|GYSA ETCHOJOA' => 1118,
            'FLETES SOTELO|GYSA OBREGON 1' => 1021,
            'FLETES SOTELO|GYSA OBREGON 2' => 1021,
            'FLETES SOTELO|GYSA OBREGON PDC' => 1021,
            'FLETES SOTELO|HUNGAROS / NOGALES' => 600,
            'GYSA  CDJ|YARDA SOTELO OBREGON' => 1021,
            'GYSA BACUM|GYSA NAVOJOA' => 112,
            'GYSA BACUM|GYSA OBREGON (CDO2)' => 45,
            'GYSA BACUM|GYSA OBREGON 2' => 45,
            'GYSA BACUM|GYSA OBREGON ODC' => 45,
            'GYSA ETCHOJOA|FLETES SOTELO' => 1118,
            'GYSA ETCHOJOA|GYSA  CDJ' => 1118,
            'GYSA ETCHOJOA|GYSA OBREGON ODC' => 97,
            'GYSA JUAREZ JDC|GYSA OBREGON 2' => 1021,
            'GYSA OBREGON 2|GYSA ETCHOJOA' => 97,
            'GYSA OBREGON PDC|GYSA BACUM' => 45,
            'GYSA OBREGON PDC|GYSA ETCHOJOA' => 97,
            'GYSA OBREGON PDC|GYSA NAVOJOA' => 67,
            'TRANSERVICIOS CHIHUAHUA|TRANSERVICIOS CD JUAREZ' => 375,
            'YARDA SOTELO OBREGON|GYSA  CDJ' => 1021,
            'YAZAKI COMPONENTES PLANTA 3|GYSA JUAREZ JDC' => 1131,
            'YAZAKI COMPONENTES PLANTA 3|GYSA OBREGON PDC' => 1131,
            'FLETES SOTELO|ARNPRIOR AEROSPACE CHIHUAHUA' => 375,
            'FLETES SOTELO|CESSNA PLANTA 4.1' => 375,
            'FLETES SOTELO|DEMINSA SA DE CV' => 800,
            'FLETES SOTELO|DTR' => 375,
            'FLETES SOTELO|FOKKER' => 375,
            'FLETES SOTELO|SAFRAN CABIN' => 375,
            'FLETES SOTELO|SAFRAN PLANTA 1 /EMX/ EVACUATION SY (AIR CRUSIERS)' => 375,
            'FLETES SOTELO|SMTC PLANTA 1' => 375,
            'FLETES SOTELO|SOUTHCO.' => 375,
            'FLETES SOTELO|XOMOX CHIHUAHUA S.A DE C.V.' => 375,
            'FLETES SOTELO|XYLEM' => 375,
            'FLETES SOTELO|YAZAKI COMPONENTES PLANTA 2' => 375,
            'FREIG CARRILLO / NOGALES AZ|GYSA  CDJ' => 800,
            'PRECOS ZARAGOZA|BASE SOTELO CHIHUAHUA' => 375,
            'PRECOS ZARAGOZA|DTR' => 375,
            'PRECOS ZARAGOZA|FOKKER' => 375,
            'PRECOS ZARAGOZA|SAFRAN CABIN' => 375,
            'PRECOS ZARAGOZA|SAFRAN PLANTA 1 /EMX/ EVACUATION SY (AIR CRUSIERS)' => 375,
            'PRECOS ZARAGOZA|SAFRAN PLANTA 3 /WWM/ WATER & WASTE MEX (MONOGRAM)' => 375,
            'PRECOS ZARAGOZA|SAFRAN PLANTA 5 / ELM / ELECTRIC MEXICO (SEPS)' => 375,
            'PRECOS ZARAGOZA|SAFRAN PLANTA 5 / LSM/ LIGHTING SOLUTIONS (IDD)' => 375,
            'PRECOS ZARAGOZA|SMTC PLANTA 1' => 375,
            'PRECOS ZARAGOZA|SOUTHCO.' => 375,
            'PRECOS ZARAGOZA|WIREMASTERS' => 375,
            'PRECOS ZARAGOZA|XYLEM' => 375,
            'PRECOS ZARAGOZA|YAZAKI COMPONENTES PLANTA 2' => 375,
            'CASETA DE VILLA AHUMADA|PRECOS ZARAGOZA' => 130,
            'CENTURY MOLD MEXICO S DE RL DE CV|FLETES SOTELO' => 375,
            'CESSNA PLANTA 4.1|BASE SOTELO CHIHUAHUA' => 375,
            'GYSA JUAREZ JDC|BASE SOTELO CHIHUAHUA' => 375,
            'YARDA SOTELO OBREGON|GYSA NAVOJOA' => 67,
        ];

        $rows = [];

        $appendRows = static function (array $routeMap, string $region) use (&$rows): void {
            foreach ($routeMap as $key => $kms) {
                [$origin, $destination] = array_map('trim', explode('|', $key, 2));
                $rows[] = [
                    'origen_normalizado' => $origin,
                    'destino_normalizado' => $destination,
                    'distancia_km' => (float) $kms,
                    'region' => $region,
                    'is_active' => 1,
                ];
            }
        };

        $appendRows($generalRoutes, 'GENERAL');
        $appendRows($pacificoRoutes, 'PACIFICO');
        $appendRows($clientRoutes, 'CLIENTE');

        $table = $this->db->table('rutas_distancias');
        $table->truncate();
        $table->insertBatch($rows);
    }
}
